name: API Laravel CI/CD

on:
  push:
    branches:
      - 'main_api'
    paths-ignore:
      - 'README.md'
      - .github/**
      - docs/**
      - 'Dockerfile'
  pull_request:
    branches:
      - 'main_api'
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - .github/**
      - docs/**
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Server 2 and Do it
      uses: appleboy/ssh-action@master
      env:
        GITHUB_SHA_X: ${GITHUB_SHA}
      with:
        host: ${{ secrets.SSH_HOST }}  
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{secrets.SSH_PORT }}
        script: |
          cd /www/wwwroot/shell 
          nohup ./batch_shell_composer.sh $GITHUB_SHA_X > /dev/null 2>&1 &
          disown    
